[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
token-mill = "2eZVMSjoarnyk7PeyapaHDRueEXML9QCRUJFuUSQhSuU"

[programs.localnet]
token-mill = "2eZVMSjoarnyk7PeyapaHDRueEXML9QCRUJFuUSQhSuU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun test"
